### ISSUE TITLE
Homepage in page scroll

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-client#174]
Explore link should trigger in page scroll

**Comment by dankerk** [comment]
I got 2 options for this. Which one is better?
I could either create a reference to the sectionsCategories component, or add a class. With the reference method I also need to import ReactDOM on the homepage.. Both work fine :)

To improve further I could also add smooth scrolling, but then it makes sense to make it reusable within the project. In that case, where should I put these extra lines of code? Could also use an available package (https://www.npmjs.com/package/react-scroll-to-component)

<SectionCategories ref={(el) => { this.categories = el; }} className="categories">

  scrollToSection2 = (elementRef) => {
    let el = ReactDOM.findDOMNode(this[elementRef]),
    target = el.getBoundingClientRect().top;
    window.scrollTo(0, window.scrollY + target);
  }
  
  scrollToSection = (sectionClassName) => {
    let el = document.querySelector('.' + sectionClassName),
    target = el.getBoundingClientRect().top;
    window.scrollTo(0, window.scrollY + target);
  }

**Comment by tmfrnz** [comment]
definitely prefer not having the classname, however also the other approach will not pass the linter I think as `findDOMNode` is deprecated or considered evil. have a look here
https://github.com/yannickcr/eslint-plugin-react/issues/678

otherwise that package looks all right too. however it is also using findDomNode albeit outside of our linter's scope =)
https://github.com/flyingant/react-scroll-to-component/blob/master/index.js#L29

btw to install new packages if you wanted to give that a try use `yarn add`

**Comment by dankerk** [comment]
Thanks for the tips. 
I got rid of the findDOMNode. It works fine now, but scrolling smoothly would be a nice add-on. I will add it tomorrow, then you can let me know afterwards if there's a better place (separate component probably) for the code.

I committed the code. Let me know if you have any furter remarks

**Comment by tmfrnz** [comment]
have you pushed also? can not see your branch...

**Comment by dankerk** [comment]
I stopped after committin, ooops.... now it's pushed onto the development branch, which I can't see on Github. Is there another branch I should be pushing it to?

**Comment by dankerk** [comment]
By the way, shouldn't you be sleeping? :P

**Comment by tmfrnz** [comment]
Ideally every feature should have its own branch, also including the issue number. You can easily create one by using the `-b` flag:
`git checkout -b awesome-feature-174`

Some conventions also include the username, eg
`dankerk-awesome-feature-174`

I have deleted the development branch earlier this week as we decided to just use master for that. However it should be re-created once you push it to GitHub I think

**Comment by dankerk** [comment]
Alright, so my Git skills were a bit rusty. Somehow I managed to lose my changes haha.
So I did a quick Git course, made the changes and commited&pushed them according to your conventions.
The only thing that went wrong is that on Github it says the commit has been done by Comheroes instead of dankerk... even though git config --global user.name has been set to dankerk so I'll have to look into that. Let me know what's next. Sorry for the learning curve..

**Comment by tmfrnz** [comment]
thanks @dankerk I can see your commit 
https://github.com/dumparkltd/hr-nmrf-client/commit/557c37aa5fad3034a0f7143d9bd19edebca04408
ideally this should have been committed to its own feature branch not master and integrated via a pull request

**Comment by dankerk** [comment]
Ah, so close! Next time... I'm now on a surftrip in Portugal, but should be able to find the time to animate that scroll this week.
