### ISSUE TITLE
Provide layout for list sorting options

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-client#232]
Both entity lists and category lists

**Comment by dmprk** [comment]
![categoryList.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46eb958e26858cbb96c5b650b01fbcd6395428792c07b7692ac7b670e6402304090b47ac48505e45affa892bf0b16f79895519f1c32f0e2a92624cf5f2d75dad0ba8228d4584b2b5834ec1ea3b21e1828c4c2c53.png)
![entityList-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ed9a8e2a969a8586faab0ef51fbcd6395428792c07b7692ac7b670e6402304090b47ac48505e45affa892bf0b16f79895519f1c32f0e2a92624cf5f2d75dad0ba8228d4584b2b5834ec1ea3b21e1828a4d2c53.png)
![entityList-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46ed9a8e2a969a8586faab0ef61fbcd6395428792c07b7692ac7b670e6402304090b47ac48505e45affa892bf0b16f79895519f1c32f0e2a92624cf5f2d75dad0ba8238a4584b2b5834ec1ea3b21e1828a4e2c53.png)
