### ISSUE TITLE
User can select page for navigating entity lists

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-client#251]
User can
- navigate to 
  - first page 
  - last page
  - next page
  - previous page
  - neighbouring pages
- select no of items on page
- see how many items are currently showing (see #232)

**Comment by dmprk** [comment]
![pagination-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46f8959d2a8c82bd86e6b10ef51fbcd6395428792c07b7692ac7b670e6402304090b47ac48505e45affa892bf0b16f79895519f1c32f0e2a92624cf5f2d75dad0ba8228d4584b2b5834fc0ed3e23e58a874c2c53.png)
![pagination-2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/556cf58fb094e61c00764138/125516c66e82c728ace21e0d46f8959d2a8c82bd86e6b10ef61fbcd6395428792c07b7692ac7b670e6402304090b47ac48505e45affa892bf0b16f79895519f1c32f0e2a92624cf5f2d75dad0ba8238a4584b2b5834fc0ed3e23e58c88472c53.png)
