### ISSUE TITLE
Basic filterable multiselect list component (categories)

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-client#32]
_From @tmfrnz on November 2, 2016 20:22_

As a user of Sadata

I want an easy to use UI element for filtering a list of categories s by keyword and choosing one or more options from the list.

_Copied from original issue: dumparkltd/hr-nmrf-server#42_

**Comment by tmfrnz** [comment]
used for filtering principal entities by category and batch assigning categories (eg human rights bodies, thematic clusters) to principal entities (recommendations - actions)

basic version of #28,

**Comment by tmfrnz** [comment]
filtering for multiple categories of same taxonomy should generally be additive ("show me all recommendations tagged with children AND indigeneous"), although it may be neessary in the future to also allow optional ("show me all recommendations of either treatybody a OR treatybody b") selections

when filtering (additive) the list of filter options should only offer those available and thus ideally be updated with every filtering action

**Comment by tmfrnz** [comment]
Used for filtering lists:
![3](https://cloud.githubusercontent.com/assets/5811956/20299006/bf92a254-ab7d-11e6-910e-a2031038a40b.png)

**Comment by tmfrnz** [comment]
Used for assigning categories
![9](https://cloud.githubusercontent.com/assets/5811956/20299037/eb5c68b6-ab7d-11e6-85ed-cba8ce506e87.png)

**Comment by tmfrnz** [comment]
![screenshot 2016-11-15 21 53 46](https://cloud.githubusercontent.com/assets/5811956/20299063/1baeb00a-ab7e-11e6-9620-0081807b699f.png)

**Comment by tmfrnz** [comment]
Used for filtering #28
![action-new-4](https://cloud.githubusercontent.com/assets/5811956/20299122/533947e2-ab7e-11e6-92a7-19a185df6a8c.png)

**Comment by tmfrnz** [comment]
Category assign: #34 and #35

**Comment by tmfrnz** [comment]
TODO:
- [ ] add keyword search field that filters options list based on label, value and new optional search attribute (see https://github.com/dumparkltd/hr-nmrf-client/commit/a3bdf2473526b2949d1b75262ed5342ee0646f53#diff-d2b2c1c036bac73fb47ce93f36b3ddddR230)
- [ ] only allow one checked option when "allowMultiple" param is false (when editing only not filtering, certain taxonomies are limited to one category, eg Human RIghts Body, Session)

**Comment by tim-field** [comment]
@tmfrnz 
"query params should not be removed on page reload" is being caused by this line.
https://github.com/dumparkltd/hr-nmrf-client/blob/development/app/containers/App/sagas.js#L138
`authenticateSuccess`
which calls 
`authChangeSaga`
which messes with the path
