### ISSUE TITLE
Contributor uploads document for progress report

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-client#52]
_From @tmfrnz on November 12, 2016 22:58_

null

_Copied from original issue: dumparkltd/hr-nmrf-server#73_

**Comment by tmfrnz** [comment]
Should the this be possible 
- for own progress report (created by contributor)
- for progress report associated with indicator contributor is assigned to?

Alternatively to consider

**Comment by tmfrnz** [comment]
@tmfrnz to consider options for uploading files directly from client to AWS S3

**Comment by tmfrnz** [comment]
question:
- [ ] is one document per progress report sufficient?

**Comment by tmfrnz** [comment]
clarify:

one common solution is to upload the documents to a web server and store the document's location (URL) in the database. However, once stored on the web server the document would remain public even when not linked from the web application unless deleted from the web-server (or moved to a non-public folder).

**Comment by tmfrnz** [comment]
eg https://github.com/odysseyscience/react-s3-uploader#ruby-on-rails-assuming-fog-usage

**Comment by tmfrnz** [comment]
@tony-luisi, @tim-field the server endpoint has been set up according to react-s3-uploader (see above). the server endpoint is `s3/sign`

**Comment by tmfrnz** [comment]
https://github.com/dumparkltd/hr-nmrf-server/issues/73

**Comment by dmprk** [comment]
![progress-edit-1](https://cloud.githubusercontent.com/assets/8222383/25786061/63630198-33e2-11e7-9149-035f891663aa.png)
![progress-edit-2](https://cloud.githubusercontent.com/assets/8222383/25786062/6363149e-33e2-11e7-93c4-400ede849e50.png)
![progress-view-public](https://cloud.githubusercontent.com/assets/8222383/25786063/63656690-33e2-11e7-8513-fce2f4f1bdaf.png)
