### ISSUE TITLE
GetEntitiesSaga runs multiple times on LOAD_ENTITIES action

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/hr-nmrf-client#74]
Entity loading tests on Home Page result in loading entities multiple times

**Comment by tmfrnz** [comment]
Possibly caused by the way LOAD_ENTITIES action is handled in rootSaga? 

https://github.com/dumparkltd/hr-nmrf-client/blob/master/app/containers/App/sagas.js#L156

**Comment by tim-field** [comment]
I've got this fixed in develop branch, need to init the app saga in store.js https://github.com/dumparkltd/hr-nmrf-client/blob/development/app/store.js#L44
