### ISSUE TITLE
Measures endpoint not responding with auth headers

### ISSUE THREAD

**Issue by tim-field** [dumparkltd/hr-nmrf-client#75]
![image](https://cloud.githubusercontent.com/assets/1326910/22905089/d2662532-f2a3-11e6-9a64-ddfe98a2196b.png)

Note the auth headers aren't being sent back here, despite being sent.

But not having the same issues with `recommendations` and `recommendation_measures`

![image](https://cloud.githubusercontent.com/assets/1326910/22905119/ed7ac166-f2a3-11e6-97d0-afb43253273b.png)

These are both responding with auth headers echoed back :+1:

**Comment by tmfrnz** [comment]
works for me once authenticated (still on feature-1 branch here locally)
![screenshot 2017-02-14 11 39 42](https://cloud.githubusercontent.com/assets/5811956/22906663/6eab980e-f2aa-11e6-8eb5-a8358a05d0ec.png)

does not return headers when not logged in, neither measures nor recs

**Comment by tim-field** [comment]
Very strange, switching to that branch doesn't help here

![image](https://cloud.githubusercontent.com/assets/1326910/22907604/c882ef0e-f2ae-11e6-80f2-bbec0dd5e217.png)

Can you paste in a screen shot of  the request headers that you are sending

**Comment by tmfrnz** [comment]
Request headers:
![screenshot 2017-02-14 12 19 25](https://cloud.githubusercontent.com/assets/5811956/22907828/f891f310-f2af-11e6-98f4-e81e81d34346.png)


One thing I noticed though is that in my local version (again outdated feature-1 branch) the request is sent twice with only the first response including the headers and not the response(s) to subsequent request(s). I wonder if this could have to do with the way devise handles "batch requests" where the token is valid for all requests within 5 seconds (or whatever time configurated) (https://github.com/lynndylanhurley/devise_token_auth#about-batch-requests)

**Comment by tim-field** [comment]
It seems to be quite random as to which request will return auth readers back

Testing on feature1 branch I often don't get auth headers back for measures or for recomendations.  I tend to get it back for one of the requests, but not all. 

So I wonder if when the server goes into batch mode, it stops echoing back auth header information for the requests in the middle of the batch ?

**Comment by tim-field** [comment]
This is the issue we are having.

https://github.com/lynndylanhurley/devise_token_auth/issues/702

So in the middle of a batch request, we don't get auth headers back.  My auth headers code is then unsetting the localstorage values as the headers are now null.  ( Which is how it should work really )

I've stopped my auth code from unsetting headers for now ( which will break logout until I restore that to be a separate unset from localStorage )
